name: Pull request

on:
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:
  
env:
  REGISTRY: kazuh.azurecr.io

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    
    - name: 📦 Cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: ⚙️ Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        
    - name: 🏗️ Build docker image
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:pull-request
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}
        cache-to: type=inline
        push: false
